//
//  ResourcingImages.swift
//  File autogenerated
//
//  Created by Jorge Morán Palomeque.
//  jorgemoranp@gmail.com
//

import Foundation
import UIKit

public class RImages {

	public let checkBoxOn: UIImage? = UIImage(named: "checkBoxOn")
	public let arrow: UIImage? = UIImage(named: "arrow")
	public let gNB_logo: UIImage? = UIImage(named: "GNB_logo")
	public let ico_eye_close: UIImage? = UIImage(named: "ico_eye_close")
	public let ico_eye_open: UIImage? = UIImage(named: "ico_eye_open")
	public let close: UIImage? = UIImage(named: "close")
	public let checkBoxOff: UIImage? = UIImage(named: "checkBoxOff")
}